name: generate-terragrunt-changes-matrix
description: Generate the matrix list output for file changes in terragrunt

inputs:
  directories:
    description: A whitespace-separated list of directories we need to build the matrix from
    required: true
outputs:
  directory-matrix:
    description: "The matrix of directories, environments, regions, and clean directory names"
    value: ${{ steps.generate-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Generate Matrix
      shell: bash
      id: generate-matrix
      run: |
        
       
        > unique_directories.out
        > environments.out

        for directory in $(echo "${{ inputs.directories }}"); do
          
          if [[ "$directory" == ".github"* || "$directory" == ".gitignore" || "$directory" == "README"* ]]; then
            continue
          fi

          
          parent_directory=$(echo "$directory" | cut -d '/' -f 1)

          
          if ! grep -qx "$parent_directory" unique_directories.out; then
            echo "$parent_directory" >> unique_directories.out
            echo "{\"directory\":\"$parent_directory\", \"environment\":\"$parent_directory\"}" >> environments.out
          fi
          done

         
          matrix=$(jq -s '.' environments.out)
          
          matrix=$(echo "$matrix" | jq -c '.')
          
          echo "$matrix"
         
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
