repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks.git
   rev: v4.4.0
   hooks:
   -  id: check-case-conflict
   -  id: check-symlinks
   -  id: detect-private-key
   -  id: trailing-whitespace
-  repo: https://github.com/antonbabenko/pre-commit-terraform.git
   rev: v1.77.1
   hooks:
   -  id: terraform_fmt
-  repo: https://github.com/terraform-docs/terraform-docs.git
   rev: v0.16.0
   hooks:
   -  id: terraform-docs-go
      args: ["markdown", "table", "--output-file", "README.md", "."]

