module "sql-database" {
  source              = "../"
  database_names      = var.database_names
  location            = var.location
  resourcetype        = var.resourcetype
  appid               = var.appid
  appname             = var.appname
  env                 = var.env
  costCostCenter      = var.costCostCenter
  costVP              = var.costVP
  costAppOwnerTech    = var.costAppOwnerTech
  costAppOwnerManager = var.costAppOwnerManager
  costBudgetOwner     = var.costBudgetOwner
  costDivision        = var.costDivision
  costAllocation      = var.costAllocation
  appFunction         = var.appFunction
  monthlyBudget       = var.monthlyBudget
  costbaseline        = var.costbaseline
  #additionalcontext   = var.additionalcontext
  environment   = var.environment
  app_id        = var.app_id
  msftmigration = var.msftmigration
}
