name                         = "test-sub-enhablement-shared-poc-01"
recurrence_type              = "Monthly"
recurrence_period_start_date = "2025-01-18T00:00:00Z"
recurrence_period_end_date   = "2027-01-18T00:00:00Z"
root_folder_path             = "cost-export"
time_frame                   = "MonthToDate"
type                         = "ActualCost"