role_definitions = {
  infra_admin = {
    name        = "infra_admin"
    description = "infra_admin can manage all resources except Network components, Blueprint, Authorization"
    scope       = "/providers/Microsoft.Management/managementGroups/mg-new"
    actions     = ["*"]
    not_actions = [
      "Microsoft.Authorization/*/Delete",
      "Microsoft.Authorization/*/Write",
      "Microsoft.Authorization/elevateAccess/Action",
      "Microsoft.Blueprint/blueprintAssignments/write",
      "Microsoft.Blueprint/blueprintAssignments/delete",
      "Microsoft.Compute/galleries/share/action",
      "Microsoft.Network/register/action",
      "Microsoft.Network/unregister/action",
      "Microsoft.Network/checkTrafficManagerNameAvailability/action",
      "Microsoft.Network/checkFrontDoorNameAvailability/action",
      "Microsoft.Network/bgpServiceCommunities/read",
      "Microsoft.Network/routeFilters/*",
      "Microsoft.Network/virtualNetworks/write",
      "Microsoft.Network/virtualNetworks/delete",
      "Microsoft.Network/virtualNetworks/joinLoadBalancer/action",
      "Microsoft.Network/virtualNetworks/peer/action",
      "Microsoft.Network/virtualNetworks/join/action",
      "Microsoft.Network/virtualNetworks/BastionHosts/action",
      "Microsoft.Network/virtualNetworks/virtualMachines/read",
      "Microsoft.Network/virtualNetworks/subnets/read",
      "Microsoft.Network/virtualNetworks/subnets/write",
      "Microsoft.Network/virtualNetworks/subnets/delete",
      "Microsoft.Network/virtualNetworks/subnets/joinLoadBalancer/action",
      "Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action",
      "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
      "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action",
      "Microsoft.Network/virtualNetworks/subnets/contextualServiceEndpointPolicies/*",
      "Microsoft.Network/virtualNetworks/subnets/virtualMachines/read",
      "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/*",
      "Microsoft.Network/virtualNetworks/checkIpAddressAvailability/read",
      "Microsoft.Network/virtualNetworks/usages/read",
      "Microsoft.Network/virtualNetworks/bastionHosts/default/action",
      "Microsoft.Network/virtualNetworks/privateDnsZoneLinks/read",
      #"Microsoft.Network/virtualNetworks/dnsResolvers/read",
      #"Microsoft.Network/virtualNetworks/dnsForwardingRulesets/read",
      "Microsoft.Network/networkWatchers/*",
      "Microsoft.Network/publicIPAddresses/*",
      "Microsoft.Network/serviceEndpointPolicies/*",
      "Microsoft.Network/networkSecurityGroups/write",
      "Microsoft.Network/networkSecurityGroups/delete",
      "Microsoft.Network/networkSecurityGroups/defaultSecurityRules/read",
      "Microsoft.Network/networkSecurityGroups/securityRules/read",
      "Microsoft.Network/networkSecurityGroups/securityRules/write",
      "Microsoft.Network/networkSecurityGroups/securityRules/delete",
      "Microsoft.Network/applicationSecurityGroups/*",
      "Microsoft.Network/routeTables/*",
      "Microsoft.Network/loadBalancers/write",
      "Microsoft.Network/loadBalancers/delete",
      "Microsoft.Network/loadBalancers/virtualMachines/read",
      "Microsoft.Network/loadBalancers/networkInterfaces/read",
      "Microsoft.Network/loadBalancers/frontendIPConfigurations/read",
      "Microsoft.Network/loadBalancers/frontendIPConfigurations/join/action",
      "Microsoft.Network/loadBalancers/backendAddressPools/queryInboundNatRulePortMapping/action",
      "Microsoft.Network/loadBalancers/backendAddressPools/read",
      "Microsoft.Network/loadBalancers/backendAddressPools/write",
      "Microsoft.Network/loadBalancers/backendAddressPools/delete",
      "Microsoft.Network/loadBalancers/inboundNatRules/read",
      "Microsoft.Network/loadBalancers/inboundNatRules/write",
      "Microsoft.Network/loadBalancers/inboundNatRules/delete",
      "Microsoft.Network/loadBalancers/inboundNatPools/read",
      "Microsoft.Network/loadBalancers/loadBalancingRules/read",
      "Microsoft.Network/loadBalancers/probes/read",
      "Microsoft.Network/loadBalancers/outboundRules/read",
      "Microsoft.Network/loadBalancers/backendAddressPools/backendPoolAddresses/read",
      "Microsoft.Network/applicationGateways/read",
      "Microsoft.Network/applicationGateways/write",
      "Microsoft.Network/applicationGateways/delete",
      "Microsoft.Network/applicationGateways/backendhealth/action",
      "Microsoft.Network/applicationGateways/getBackendHealthOnDemand/action",
      "Microsoft.Network/applicationGateways/start/action",
      "Microsoft.Network/applicationGateways/stop/action",
      "Microsoft.Network/applicationGateways/restart/action",
      "Microsoft.Network/applicationGateways/migrateV1ToV2/action",
      "Microsoft.Network/applicationGateways/getMigrationStatus/action",
      "Microsoft.Network/applicationGateways/privateLinkResources/read",
      "Microsoft.Network/applicationGateways/privateEndpointConnections/read",
      "Microsoft.Network/applicationGateways/privateEndpointConnections/write",
      "Microsoft.Network/applicationGateways/privateEndpointConnections/delete",
      "Microsoft.Network/applicationGateways/privateLinkConfigurations/read",
      "Microsoft.Network/applicationGatewayAvailableWafRuleSets/read",
      "Microsoft.Network/applicationGatewayAvailableSslOptions/read",
      "Microsoft.Network/applicationGatewayAvailableSslOptions/predefinedPolicies/read",
      "Microsoft.Network/trafficManagerProfiles/*",
      "Microsoft.Network/trafficManagerGeographicHierarchies/read",
      "Microsoft.Network/trafficManagerUserMetricsKeys/*",
      #   "Microsoft.Network/dnszones/*",
      #   "Microsoft.Network/dnsoperationresults/read",
      #   "Microsoft.Network/dnsoperationstatuses/read",
      "Microsoft.Network/operations/*",
      "Microsoft.Network/expressRouteCircuits/*",
      "Microsoft.Network/expressRouteServiceProviders/read",
      "Microsoft.Network/connections/*",
      "Microsoft.Network/virtualnetworkgateways/supportedvpndevices/action",
      "Microsoft.Network/virtualNetworkGateways/*",
      "microsoft.network/virtualnetworkgateways/*",
      "Microsoft.Network/localnetworkgateways/*",
      "Microsoft.Network/virtualNetworkTaps/*",
      "Microsoft.Network/virtualWans/*",
      "Microsoft.Network/virtualwans/*",
      "Microsoft.Network/vpnsites/*",
      "Microsoft.Network/virtualHubs/*",
      "Microsoft.Network/expressRouteCrossConnections/*",
      "Microsoft.Network/ddosProtectionPlans/*",
      "Microsoft.Network/vpnGateways/*",
      "microsoft.network/vpngateways/*",
      "microsoft.network/vpnGateways/*",
      "Microsoft.Network/expressRoutePorts/*",
      "Microsoft.Network/networkProfiles/*",
      "Microsoft.Network/networkIntentPolicies/*",
      "Microsoft.Network/publicIPPrefixes/*",
      "Microsoft.Network/frontDoors/*",
      "Microsoft.Network/azurefirewalls/*",
      "Microsoft.Network/networkWatchers/*",
      "Microsoft.Network/expressRouteGateways/*",
      "Microsoft.Network/privateLinkServices/*",
      "Microsoft.Network/azureFirewallFqdnTags/read",
      "Microsoft.Network/p2sVpnGateways/*",
      "microsoft.network/p2sVpnGateways/*",
      "Microsoft.Network/ddosCustomPolicies/*",
      "Microsoft.Network/natGateways/*",
      "Microsoft.Network/bastionHosts/*",
      "Microsoft.Network/frontDoorWebApplicationFirewallPolicies/*",
      "Microsoft.Network/applicationGatewayAvailableServerVariables/read",
      "Microsoft.Network/applicationGatewayAvailableRequestHeaders/read",
      "Microsoft.Network/applicationGatewayAvailableResponseHeaders/read",
      "Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/*",
      "Microsoft.Network/privateEndpoints/*",
      "Microsoft.Network/frontDoorWebApplicationFirewallManagedRuleSets/read",
      #   "Microsoft.Network/privateDnsZones/*",
      #   "Microsoft.Network/privateDnsOperationResults/read",
      #   "Microsoft.Network/privateDnsOperationStatuses/read",
      "Microsoft.Network/firewallPolicies/*",
      "microsoft.network/vpnSites/vpnSiteLinks/read",
      "Microsoft.Network/privateEndpointRedirectMaps/*",
      "Microsoft.Network/virtualRouters/*",
      "Microsoft.Network/vpnServerConfigurations/*",
      "Microsoft.Network/ipGroups/*",
      "Microsoft.Network/ipAllocations/*",
      "Microsoft.Network/networkExperimentProfiles/*",
      "Microsoft.Network/securityPartnerProviders/*",
      "Microsoft.Network/customIpPrefixes/*",
      "Microsoft.Network/masterCustomIpPrefixes/*",
      "Microsoft.Network/dscpConfiguration/*",
      "Microsoft.Network/azureFirewalls/*",
      "Microsoft.Network/azureWebCategories/read",
      "microsoft.network/virtualNetworkGateways/*",
      #   "Microsoft.Network/dnsResolvers/*",
      "Microsoft.Network/networkVirtualAppliances/*"
    ]
    data_actions     = []
    not_data_actions = []
    assignable_scopes = [
      "/providers/Microsoft.Management/managementGroups/mg-new"
    ]
} }
