name: Terragrunt Plan and Apply
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment"
        required: true
    secrets:
      app_id_01:
        required: true
      app_key_01:
        required: true

defaults:
  run:
    shell: bash

jobs:
  terragrunt-plan:
    name: "Terragrunt Plan"
    runs-on: vm-github-runner-azure-us-central-001
    environment: ${{ inputs.environment }}
    env:
      # ARM_USE_OIDC: true
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Git Config
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terragrunt installer
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: v0.67.6

      - name: Prerequisites
        uses: CenturyLink/tf-modules-azure/.github/actions/terraform-prerequisites@main
        with:
          environment: ${{ inputs.environment }}
          
      - name: TerragruntPlan
        uses: CenturyLink/tf-modules-azure/.github/actions/terragrunt-plan@main
        with:
          environment: ${{ inputs.environment }}
          app-id: ${{ secrets.app_id_01 }}
          private-key: ${{ secrets.app_key_01 }}
        env:
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  terragrunt_apply:
    name: "Terragrunt Apply"
    if: needs.terragrunt-plan.result == 'success'
    needs: terragrunt-plan
    runs-on: vm-github-runner-azure-us-central-001
    env:
      # ARM_USE_OIDC: true
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    environment: ${{ inputs.environment }}_deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terragrunt installer
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: v0.67.6

      - name: TerragruntApply
        uses: CenturyLink/tf-modules-azure/.github/actions/terragrunt-apply@main
        with:
          environment: ${{ inputs.environment }}
          app-id: ${{ secrets.app_id_01 }}
          private-key: ${{ secrets.app_key_01 }}
        env:
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}