module "openai" {
  source                             = "github.com/CenturyLink/tf-modules-azure/openai?ref=1.5.1"
  additionalcontext                  = var.additionalcontext
  appFunction                        = var.appFunction
  appid                              = var.appid
  appname                            = var.appname
  capacity                           = var.capacity
  costAllocation                     = var.costAllocation
  costAppOwnerManager                = var.costAppOwnerManager
  costAppOwnerTech                   = var.costAppOwnerTech
  costBaseline                       = var.costBaseline
  costBudgetOwner                    = var.costBudgetOwner
  costCostCenter                     = var.costCostCenter
  costDivision                       = var.costDivision
  costVP                             = var.costVP
  custom_subdomain_name              = var.custom_subdomain_name
  deployments                        = var.deployments
  env                                = var.env
  fqdns                              = var.fqdns
  key_vault_name                     = var.key_vault_name
  key_vault_resource_group_name      = var.key_vault_resource_group_name
  local_auth_enabled                 = var.local_auth_enabled
  location                           = var.location
  monthlyBudget                      = var.monthlyBudget
  network_acls_default_action        = var.network_acls_default_action
  network_acls_ip_rules              = var.network_acls_ip_rules
  network_acls_virtual_network_rules = var.network_acls_virtual_network_rules
  outbound_network_access_restricted = var.outbound_network_access_restricted
  pe_subnet_name                     = var.pe_subnet_name
  public_network_access_enabled      = var.public_network_access_enabled
  resourcetype                       = "openai"
  resource_group_name                = var.resource_group_name
  sku_name                           = var.sku_name
  vnet_name                          = var.vnet_name
}